language: ruby
rvm:
- 2.2.2
- 2.1.1
- 1.9.3
deploy:
  provider: rubygems
  api_key:
    secure: WQnBmi+DIi18NXL+iCZZ9gV8YEEmLQ8LOQY/nZ7fnnX1ziHpUDZjneXAP7t762d6dNYib8f6Bs5n+HltAhrKiyY+t/jErmjS3DR1UV2uv+/lZgu0KwxA9WSph5LBLKDYw1R+fWf6E7nlnm4+fhhT19Qr5VaL7Wsf9ojiv+RCl9U=
  gemspec: my-gemspec.gemspec
  gem: minimart
  on:
    tags: true
    repo: electric-it/minimart
